### ISSUE TITLE
Consider adding other PHP 7.x versions on Travis CI build

### ISSUE THREAD

**Issue by peter279k** [K-Phoen/Rusty#5]
As title, I notice that this repo has only `php-7.0` version test on Travis CI build.

And I think we should consider adding other `php-7.x` versions to accomplish this issue :).

**Comment by K-Phoen** [comment]
Agreed :)

Would you want to submit a PR for that?

**Comment by peter279k** [comment]
@K-Phoen. Thanks for your reply.

You can assign me directly and I can work on that.
